/*
 * Copyright (c) 2024 Microchip
 *
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef _SOC_MICROCHIP_PIC32CXBZ2_SOC_H_
#define _SOC_MICROCHIP_PIC32CXBZ2_SOC_H_

#ifndef _ASMLANGUAGE

#define DONT_USE_CMSIS_INIT

#include <zephyr/types.h>

#if defined(CONFIG_SOC_PIC32CX1012BZ25048)
#include <pic32cx1012bz25048.h>

#else
#error Library does not support the specified device.
#endif

#endif /* _ASMLANGUAGE */

#define SOC_MICROCHIP_PIC32CXBZ2_OSC32K_FREQ_HZ 32768
#define SOC_MICROCHIP_PIC32CXBZ2_DFLL48_FREQ_HZ 48000000

/** Processor Clock (HCLK) Frequency */
#define SOC_MICROCHIP_PIC32CXBZ2_HCLK_FREQ_HZ 	CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC
/** Master Clock (MCK) Frequency */
#define SOC_MICROCHIP_PIC32CXBZ2_MCK_FREQ_HZ 	SOC_MICROCHIP_PIC32CXBZ2_HCLK_FREQ_HZ
#define SOC_MICROCHIP_PIC32CXBZ2_GCLK0_FREQ_HZ 	SOC_MICROCHIP_PIC32CXBZ2_MCK_FREQ_HZ
#define SOC_MICROCHIP_PIC32CXBZ2_GCLK2_FREQ_HZ 	48000000

#define SOC_ATMEL_SAM0_HCLK_FREQ_HZ 			CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC
#define SOC_ATMEL_SAM0_MCK_FREQ_HZ 				SOC_MICROCHIP_PIC32CXBZ2_HCLK_FREQ_HZ
#define SOC_ATMEL_SAM0_GCLK0_FREQ_HZ 			SOC_MICROCHIP_PIC32CXBZ2_MCK_FREQ_HZ
#define SOC_ATMEL_SAM0_GCLK2_FREQ_HZ 			48000000

#endif /* _SOC_MICROCHIP_PIC32CXSG41_SOC_H_ */
